

// ? charAt()
//  let kurs="modern web geliştirme kursu";
// let index=kurs.charAt(5); //n harfini basar
// console.log(index)


// ? concat
// let tarih="1022"
// let sonuc=kurs.concat(" ",tarih, " ");//birleştiriyo kopyasını yazdırıyor
// console.log(sonuc)


//? indexof
//  let index=kurs.indexOf("m") //karakteri verip indexini alcaz
//  console.log(index)

//? lastIndexOf
// let index=kurs.lastIndexOf("kursu");//karakteri verip indexini indexof aynı gibi alcaz
// console.log(index)

//? toUpperCase() KELİMELERİN HEPSİNİ BÜYÜK HALA CEVİRİR
// let index=kurs.toUpperCase();
// console.log(index)

//? toLowerCase() KELİMELERİN HEPSİNİ KÜÇÜK HALA CEVİRİR
// let index=kurs.toLowerCase();
// console.log(index)

 //? trim boslukaları sıler
// let kurs="   modern web geliştirme kursu";
// console.log(kurs.trim())


//? slice ıstenilen alanı basar ekrana
// let kurs="modern web geliştirme kursu";
// console.log(kurs.slice(0,4))//mode yazar


//? substring ıstenilen alanı basar ekrana slice hiçbir farkı yok
// let kurs="modern web geliştirme kursu";
// console.log(kurs.slice(0,4))//mode yazar

 //?replace değiştirilmiş halini yazar
// let kurs="modern web geliştirme kursu";
// console.log(kurs.replace("modern","güncel"))//değiştirilmiş halini yazar




//?split  ayrıcıya göre ayırıp dizi yazar
// let kurs="modern web geliştirme kursu";
// console.log(kurs.split(" "))//ben kelimeleri neye göre ayırıyım der bosluga göre ayırıp dizi yapr